export const ALL_TYPES: string[] = [
  "Normal",
  "Fuego",
  "Agua",
  "Eléctrico",
  "Planta",
  "Hielo",
  "Lucha",
  "Veneno",
  "Tierra",
  "Volador",
  "Psíquico",
  "Bicho",
  "Roca",
  "Fantasma",
  "Dragón",
  "Siniestro",
  "Acero",
  "Hada",
];

export const TYPE_COLORS: { [key: string]: string } = {
  Bicho: "#a5ff4c",
  Dragón: "#3c6eff",
  Hada: "#fbadff",
  Fuego: "#ff9952",
  Fantasma: "#5a68eb",
  Tierra: "#df9234",
  Normal: "#cccccc",
  Psíquico: "#ff97b0",
  Acero: "#7cb1f1",
  Siniestro: "#5b5769",
  Eléctrico: "#fffe4a",
  Lucha: "#ff4848",
  Volador: "#abc4e2",
  Planta: "#63cc3b",
  Hielo: "#a1eff4",
  Veneno: "#ce7aff",
  Roca: "#dbc097",
  Agua: "#6ca6ff",
};

export const EN_TO_ES: { [key: string]: string } = {
  normal: "Normal",
  fire: "Fuego",
  water: "Agua",
  electric: "Eléctrico",
  grass: "Planta",
  ice: "Hielo",
  fighting: "Lucha",
  poison: "Veneno",
  ground: "Tierra",
  flying: "Volador",
  psychic: "Psíquico",
  bug: "Bicho",
  rock: "Roca",
  ghost: "Fantasma",
  dragon: "Dragón",
  dark: "Siniestro",
  steel: "Acero",
  fairy: "Hada",
};
